"""Optional routing for traffic generated by the Pi itself."""

from __future__ import annotations

import ipaddress
import re
import socket
from dataclasses import dataclass
from pathlib import Path

from .command_runner import CommandRunner
from .errors import GatewayError, ValidationError
from .storage import read_json

_INTERFACE_PATTERN = re.compile(r"^[A-Za-z0-9_.:-]+$")
HOST_ROUTING_TABLE = 101


@dataclass(frozen=True)
class HostRoutingConfig:
    """Validated, Pi-local policy-routing settings."""

    enabled: bool
    local_network: str | None = None
    source_address: str | None = None
    lan_interface: str = "eth0"
    lan_gateway: str | None = None
    routing_table: int = HOST_ROUTING_TABLE
    rule_priority: int = 1000

    @classmethod
    def from_document(cls, document: dict) -> "HostRoutingConfig":
        """Load the optional host-routing block without changing legacy defaults."""
        raw = document.get("host_routing")
        if raw is None:
            return cls(enabled=False)
        if not isinstance(raw, dict):
            raise ValidationError("host_routing must be an object", code="CONFIG_INVALID")

        enabled = raw.get("enabled", False)
        if not isinstance(enabled, bool):
            raise ValidationError("host_routing.enabled must be boolean", code="CONFIG_INVALID")

        local_network_value = raw.get("local_network", document.get("local_network"))
        source_address_value = raw.get("source_address")
        gateway_value = raw.get("lan_gateway")
        if not enabled:
            return cls(
                enabled=False,
                local_network=_canonical_network(local_network_value),
                source_address=_canonical_ipv4(source_address_value),
                lan_interface=_interface(raw.get("lan_interface", "eth0"), "lan_interface"),
                lan_gateway=_canonical_ipv4(gateway_value),
                routing_table=_table_id(raw.get("routing_table", HOST_ROUTING_TABLE)),
                rule_priority=_priority(raw.get("rule_priority", 1000)),
            )

        local_network = _canonical_network(local_network_value)
        source_address = _canonical_ipv4(source_address_value)
        lan_gateway = _canonical_ipv4(gateway_value)
        if local_network is None or source_address is None or lan_gateway is None:
            raise ValidationError(
                "enabled host_routing requires local_network, source_address, and lan_gateway",
                code="CONFIG_INVALID",
            )
        network = ipaddress.ip_network(local_network)
        if ipaddress.ip_address(source_address) not in network:
            raise ValidationError("host_routing.source_address must be inside local_network", code="CONFIG_INVALID")
        if ipaddress.ip_address(lan_gateway) not in network:
            raise ValidationError("host_routing.lan_gateway must be inside local_network", code="CONFIG_INVALID")

        return cls(
            enabled=True,
            local_network=local_network,
            source_address=source_address,
            lan_interface=_interface(raw.get("lan_interface", "eth0"), "lan_interface"),
            lan_gateway=lan_gateway,
            routing_table=_table_id(raw.get("routing_table", HOST_ROUTING_TABLE)),
            rule_priority=_priority(raw.get("rule_priority", 1000)),
        )


class HostRoutingService:
    """Reconcile one isolated policy table for locally generated Pi traffic."""

    def __init__(self, config_path: Path, runner: CommandRunner, interface: str = "wg0") -> None:
        """Create a host-routing module around the existing command adapter."""
        if not _INTERFACE_PATTERN.fullmatch(interface):
            raise ValidationError("WireGuard interface name is invalid", code="CONFIG_INVALID")
        self.config_path = config_path
        self.runner = runner
        self.interface = interface

    def restore(self) -> dict:
        """Apply configured host routing after WireGuard is ready, or remove it when disabled."""
        if not self.config_path.exists():
            return {"enabled": False, "restored": False}
        document = read_json(self.config_path)
        if "host_routing" not in document:
            return {"enabled": False, "restored": False}
        config = HostRoutingConfig.from_document(document)
        if not config.enabled:
            self.remove(config)
            return {"enabled": False, "restored": False}
        endpoint = self._current_endpoint()
        self.prepare(endpoint, config)
        self._prune_endpoint_routes(config, self._resolve_endpoint(endpoint))
        return {"enabled": True, "restored": True, "routing_table": config.routing_table}

    def prepare(self, endpoint: str, config: HostRoutingConfig | None = None) -> None:
        """Install exceptions and the local rule before a WireGuard peer switch."""
        config = config or self._load_config()
        if not config.enabled:
            return
        endpoint_ip = self._resolve_endpoint(endpoint)
        self._replace_route(
            [
                "ip",
                "-4",
                "route",
                "replace",
                config.local_network,
                "dev",
                config.lan_interface,
                "src",
                config.source_address,
                "table",
                str(config.routing_table),
            ]
        )
        self._replace_route(
            [
                "ip",
                "-4",
                "route",
                "replace",
                f"{endpoint_ip}/32",
                "via",
                config.lan_gateway,
                "dev",
                config.lan_interface,
                "src",
                config.source_address,
                "table",
                str(config.routing_table),
            ]
        )
        self._replace_route(
            [
                "ip",
                "-4",
                "route",
                "replace",
                "default",
                "dev",
                self.interface,
                "table",
                str(config.routing_table),
            ]
        )
        self._ensure_rule(config)

    def remove(self, config: HostRoutingConfig | None = None) -> None:
        """Remove only the policy rule and routes owned by this module."""
        config = config or self._load_config()
        self.runner.run(
            [
                "ip",
                "-4",
                "rule",
                "del",
                "pref",
                str(config.rule_priority),
                "iif",
                "lo",
                "lookup",
                str(config.routing_table),
            ],
            check=False,
        )
        self.runner.run(
            [
                "ip",
                "-4",
                "route",
                "flush",
                "table",
                str(config.routing_table),
            ],
            check=False,
        )

    def _load_config(self) -> HostRoutingConfig:
        """Read the Pi-owned configuration at operation time for safe migration."""
        if not self.config_path.exists():
            return HostRoutingConfig(enabled=False)
        return HostRoutingConfig.from_document(read_json(self.config_path))

    def _current_endpoint(self) -> str:
        """Read the active endpoint without exposing peer keys or private material."""
        result = self.runner.run(["wg", "show", self.interface, "endpoints"])
        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) == 2:
                return parts[1]
        raise GatewayError("WG_ENDPOINT_NOT_FOUND", f"No active endpoint found on {self.interface}")

    def _resolve_endpoint(self, endpoint: str) -> str:
        """Resolve a configured IPv4 endpoint into the route exception address."""
        host, separator, _port = endpoint.rpartition(":")
        if not separator or not host:
            raise GatewayError("INVALID_ENDPOINT", "WireGuard endpoint has no valid host")
        try:
            address = ipaddress.ip_address(host)
        except ValueError:
            try:
                addresses = socket.getaddrinfo(host, None, socket.AF_INET, socket.SOCK_DGRAM)
            except OSError as error:
                raise GatewayError("ENDPOINT_RESOLUTION_FAILED", "WireGuard endpoint could not be resolved") from error
            if not addresses:
                raise GatewayError("ENDPOINT_RESOLUTION_FAILED", "WireGuard endpoint has no IPv4 address")
            address = ipaddress.ip_address(addresses[0][4][0])
        if address.version != 4:
            raise GatewayError("INVALID_ENDPOINT", "Host routing requires an IPv4 WireGuard endpoint")
        return str(address)

    def _ensure_rule(self, config: HostRoutingConfig) -> None:
        """Add the local-output selector once, leaving forwarded client rules untouched."""
        result = self.runner.run(["ip", "-4", "rule", "show"])
        expected_priority = f"{config.rule_priority}:"
        expected_table = str(config.routing_table)
        if any(
            line.split()[:1] == [expected_priority]
            and "iif" in line.split()
            and line.split()[line.split().index("iif") + 1 : line.split().index("iif") + 2] == ["lo"]
            and "lookup" in line.split()
            and line.split()[line.split().index("lookup") + 1 : line.split().index("lookup") + 2] == [expected_table]
            for line in result.stdout.splitlines()
        ):
            return
        self.runner.run(
            [
                "ip",
                "-4",
                "rule",
                "add",
                "pref",
                str(config.rule_priority),
                "iif",
                "lo",
                "lookup",
                str(config.routing_table),
            ]
        )

    def _replace_route(self, command: list[str]) -> None:
        """Execute one idempotent route replacement through the non-shell runner."""
        self.runner.run(command)

    def _prune_endpoint_routes(self, config: HostRoutingConfig, current_endpoint: str) -> None:
        """Remove stale endpoint exceptions from the dedicated policy table."""
        result = self.runner.run(["ip", "-4", "route", "show", "table", str(config.routing_table)], check=False)
        for line in result.stdout.splitlines():
            parts = line.split()
            if not parts or parts[0] == "default" or parts[0] == config.local_network:
                continue
            if "via" not in parts or config.lan_gateway not in parts:
                continue
            destination = _host_route_destination(parts[0])
            if destination is None:
                continue
            if destination == current_endpoint:
                continue
            self.runner.run(
                ["ip", "-4", "route", "del", f"{destination}/32", "table", str(config.routing_table)],
                check=False,
            )

def _canonical_network(value: object) -> str | None:
    """Return a canonical IPv4 network or no value for disabled configuration."""
    if value is None:
        return None
    try:
        network = ipaddress.ip_network(str(value), strict=False)
    except ValueError as error:
        raise ValidationError("local_network must be a valid IPv4 network", code="CONFIG_INVALID") from error
    if network.version != 4:
        raise ValidationError("local_network must be IPv4", code="CONFIG_INVALID")
    return str(network)


def _canonical_ipv4(value: object) -> str | None:
    """Return a canonical IPv4 address or no value for disabled configuration."""
    if value is None:
        return None
    try:
        address = ipaddress.ip_address(str(value))
    except ValueError as error:
        raise ValidationError("host_routing addresses must be valid IPv4 addresses", code="CONFIG_INVALID") from error
    if address.version != 4:
        raise ValidationError("host_routing addresses must be IPv4", code="CONFIG_INVALID")
    return str(address)


def _interface(value: object, field: str) -> str:
    """Validate an interface name before passing it to the command adapter."""
    if not isinstance(value, str) or not _INTERFACE_PATTERN.fullmatch(value):
        raise ValidationError(f"{field} is invalid", code="CONFIG_INVALID")
    return value


def _table_id(value: object) -> int:
    """Validate the reserved host table without touching device table 100."""
    if value != HOST_ROUTING_TABLE:
        raise ValidationError(
            f"host_routing.routing_table is fixed at {HOST_ROUTING_TABLE}",
            code="CONFIG_INVALID",
        )
    return HOST_ROUTING_TABLE


def _priority(value: object) -> int:
    """Validate a policy-rule priority that runs before the main table."""
    if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value <= 32765:
        raise ValidationError("rule_priority must be between 1 and 32765", code="CONFIG_INVALID")
    return value


def _host_route_destination(value: str) -> str | None:
    """Normalize iproute2's abbreviated host-route destination output."""
    try:
        network = ipaddress.ip_network(value, strict=False)
    except ValueError:
        try:
            address = ipaddress.ip_address(value)
        except ValueError:
            return None
        return str(address) if address.version == 4 else None
    if network.version != 4 or network.prefixlen != 32:
        return None
    return str(network.network_address)
